name: nanna-example
version: '0.1'

services:
  database_postgres:
    container_name: database_postgres
    image: postgres
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pwd
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./Volumes/database:/var/lib/postgresql/data
    ports:
      - "5488:5432"
